

export const FETCH_JOB_LISTINGS_REQUEST = 'FETCH_JOB_LISTINGS_REQUEST';
export const FETCH_JOB_LISTINGS_SUCCESS = 'FETCH_JOB_LISTINGS_SUCCESS';
export const FETCH_JOB_LISTINGS_FAILURE = 'FETCH_JOB_LISTINGS_FAILURE';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';